name: Main-Windows 

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  build_and_test:

    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
      fail-fast: false

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive 

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install global python dependencies
        run: |
          python -m pip install --upgrade pip 
          python -m pip install --upgrade virtualenv
          python -m pip install --upgrade nox 

      - name: Warm up virtualenv cache
        run: |
          ./virtualenv_warmup.sh

      - name: Test with nox
        run: |
          nox 
