name: Main-Simple

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  build_and_test:

    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]

    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive 

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install global python dependencies
        run: |
          python -m pip install --upgrade pip 
          python -m pip install --upgrade pytest 

      - name: Install our package
        run: |
          pip install .
 
      - name: Test with pytest
        run: |
          pytest test 
